server:
  port: 9090

security:
  sessions: ALWAYS


---


spring:
  profiles: docker
  redis:
    host: redis
    port: 6379
  zipkin:
    baseUrl: http://zipkin:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      cluster: PheonixPlatform
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${pheonix.services.eureka.uri}:8761/eureka/


---


spring:
  profiles: dev
  redis:
    host: localhost
    port: 6379
  zipkin:
    baseUrl: http://localhost:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

eureka:
  instance:
    preferIpAddress: true
    metadataMap:
      cluster: PheonixPlatform
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/